import Foundation

// Keep diagnostics, update, interaction, and session-detail copy together because they are mostly action/status strings.
extension AppText {
    static let hooksAndSessionStrings: [String: String] = [
        "editor_bridges": "编辑器桥接",
        "editor_bridge_live": "已连接",
        "editor_bridge_installed": "可用",
        "editor_bridge_unavailable": "不可用",
        "editor_bridge_live_detail": "应用当前正在运行",
        "editor_bridge_installed_detail": "支持原生 URI / 应用接管",
        "editor_bridge_unavailable_detail": "未安装编辑器应用",
        "editor_extension_installed": "扩展已安装",
        "editor_extension_missing": "扩展未安装",
        "install_extension": "安装扩展",
        "reinstall_extension": "重装扩展",
        "uninstall_extension": "卸载扩展",
        "cli_integrations": "CLI 集成",
        "cli_state_active": "已激活",
        "cli_state_installed": "已配置",
        "cli_state_not_installed": "已检测",
        "cli_state_cli_missing": "缺少 CLI",
        "cli_state_disabled": "已关闭",
        "open_app": "打开应用",
        "open_config": "打开配置",
        "cli_status": "CLI 状态",
        "activated": "已激活",
        "not_installed": "未安装",
        "not_detected": "未检测到",
        "management": "管理",
        "hooks_health": "集成健康度",
        "hooks_health_ok": "当前所有已启用集成都正常。",
        "hooks_health_attention": "需要处理",
        "hooks_health_enabled_active": "已启用且正常",
        "hooks_health_enabled_issues": "已启用但需修复",
        "hooks_health_disabled": "已禁用",
        "hooks_refresh_status": "刷新状态",
        "hooks_repair": "修复已启用项",
        "hooks_repaired": "已修复",
        "hooks_repair_not_needed": "没有需要修复的项",
        "reinstall": "重新安装",
        "uninstall": "卸载",
        "hooks_installed": "Hooks 安装成功",
        "install_failed": "安装失败",
        "hooks_uninstalled": "Hooks 已卸载",
        "diagnostics": "诊断",
        "diagnostics_export_archive": "导出诊断归档",
        "diagnostics_export_desc": "把实时会话状态、Hook 配置、用量缓存、macOS 信息和最近的 SuperIsland 日志打包成 zip 归档。",
        "diagnostics_save_title": "导出 SuperIsland 诊断信息",
        "diagnostics_save_filename": "SuperIsland-诊断信息.zip",
        "diagnostics_exported_format": "诊断信息已导出到 %@",
        "diagnostics_exported_with_warnings_format": "诊断信息已导出，包含 %d 条警告：%@",

        "about_desc1": "macOS 上的 AI 编码 Agent 实时状态面板",
        "about_desc2": "把会话、审批和工作区跳转集中到一个入口",
        "settings_title": "SuperIsland 设置",
        "settings_ellipsis": "设置...",
        "close": "关闭",
        "check_for_updates": "检查更新...",
        "check_for_updates_short": "检查更新",
        "reinstall_hooks": "重新安装 Hooks",
        "remove_hooks": "卸载 Hooks",
        "quit": "退出",

        "update_available_title": "发现新版本",
        "update_available_body": "SuperIsland %@ 已发布（当前版本：%@），是否立即更新？",
        "update_badge": "更新",
        "download_update": "前往下载",
        "later": "稍后",
        "no_update_title": "已是最新版本",
        "no_update_body": "SuperIsland %@ 已是最新版本。",
        "ok": "好",
        "update_now": "立即更新",
        "update_downloading": "正在下载更新...",
        "update_downloading_short": "更新中...",
        "update_progress_title": "正在安装更新",
        "update_progress_prepare": "正在准备更新...",
        "update_progress_download_percent": "正在下载更新... %d%%",
        "update_progress_mounting": "正在打开安装包...",
        "update_progress_installing": "正在安装新版本...",
        "update_progress_relaunching": "正在重新启动 SuperIsland...",
        "update_progress_detail": "安装完成后，SuperIsland 会自动重新打开。",
        "update_failed_title": "更新失败",
        "update_failed_body": "无法安装更新：%@",
        "update_manual_download": "手动下载",
        "update_homebrew_title": "发现新版本",
        "update_homebrew_body": "SuperIsland %@ 已发布。由于您通过 Homebrew 安装，请运行：",
        "update_homebrew_command": "brew upgrade superisland",
        "update_copy_command": "复制命令",

        "mute": "静音",
        "enable_sound_tooltip": "开启音效",
        "settings": "设置",
        "cancel": "取消",
        "deny": "拒绝",
        "allow_once": "允许一次",
        "always": "始终允许",
        "type_answer": "输入回答…",
        "type_message": "继续给 Codex 发消息…",
        "skip": "跳过",
        "submit": "提交",
        "send": "发送",
        "open_path": "打开",
        "copy_session_id": "复制会话 ID",

        "status_running": "运行中",
        "status_waiting": "等待中",
        "status_processing": "处理中",
        "status_idle": "空闲",
        "session_detail_status_interrupted": "已中断",
        "session_detail_status_waiting_approval": "等待审批",
        "session_detail_status_waiting_question": "等待回答",
        "session_detail_review_approval": "处理审批",
        "session_detail_answer_question": "回答问题",
        "session_detail_go_to_terminal": "前往终端",
        "session_detail_open_in_format": "用 %@ 打开",
        "session_detail_new_messages": "%d 条新消息",
        "session_detail_approval_short": "审批",
        "session_detail_question_short": "问题",
        "session_detail_conversation": "会话记录",
        "session_detail_no_history": "暂无会话记录",
        "other": "其他",
        "n_sessions": "个会话",
        "scroll_for_more": "向下滚动查看更多",
        "scroll_hidden": "个未显示",
        "lines": "行"
    ]
}
