import Foundation

// Group behavior, appearance, mascot, sound, and testing copy because these settings tabs are edited together most often.
extension AppText {
    static let behaviorAndTestingStrings: [String: String] = [
        "display_section": "显示",
        "hide_in_fullscreen": "全屏时隐藏",
        "hide_in_fullscreen_desc": "当任意应用进入全屏模式时自动隐藏面板",
        "hide_when_no_session": "无活跃会话时自动隐藏",
        "hide_when_no_session_desc": "没有 AI Agent 运行时完全隐藏面板",
        "smart_suppress": "智能抑制",
        "smart_suppress_desc": "Agent 所在终端标签页在前台时不自动展开面板",
        "collapse_on_mouse_leave": "鼠标离开时自动收起",
        "collapse_on_mouse_leave_desc": "鼠标移出展开的面板后自动收回到刘海状态",
        "completion_card_display_time": "完成卡片展示时长",
        "completion_card_display_time_desc": "任务完成后，完成卡片自动收起前保持展开的时间",
        "shortcuts": "快捷键",
        "shortcut_recording": "请按下快捷键…",
        "shortcut_none": "未设置",
        "shortcut_togglePanel": "切换面板",
        "shortcut_togglePanel_desc": "展开或收起 SuperIsland 面板",
        "shortcut_approve": "批准",
        "shortcut_approve_desc": "批准当前权限请求",
        "shortcut_approveAlways": "始终批准",
        "shortcut_approveAlways_desc": "批准并记住本次会话",
        "shortcut_deny": "拒绝",
        "shortcut_deny_desc": "拒绝当前权限请求",
        "shortcut_skipQuestion": "跳过问题",
        "shortcut_skipQuestion_desc": "跳过当前问答提示",
        "shortcut_jumpToTerminal": "跳转终端",
        "shortcut_jumpToTerminal_desc": "切换到当前活跃会话的终端",
        "shortcut_conflict": "与以下快捷键冲突:",
        "sessions": "会话",
        "session_cleanup": "空闲会话清理",
        "session_cleanup_desc": "自动移除超过指定时间没有活动的会话",
        "no_cleanup": "不清理",
        "10_minutes": "10 分钟",
        "30_minutes": "30 分钟",
        "1_hour": "1 小时",
        "2_hours": "2 小时",
        "1_day": "1 天",
        "tool_history_limit": "工具历史上限",
        "tool_history_limit_desc": "每个会话显示的最近工具调用数量上限",

        "panel": "面板",
        "custom_notch_width": "使用自定义刘海宽度",
        "notch_width": "刘海宽度",
        "notch_width_desc": "覆盖刘海模式下默认自动计算的刘海宽度。",
        "max_visible_sessions": "最大显示会话数",
        "max_visible_sessions_desc": "超出数量的会话将通过滚动查看",
        "session_grouping": "会话分组",
        "group_all": "单列表",
        "group_project": "按项目",
        "group_status": "按状态",
        "group_cli": "按 CLI",
        "group_all_compact": "全部",
        "group_project_compact": "项目",
        "group_status_compact": "状态",
        "group_cli_compact": "来源",
        "default": "默认",
        "content": "内容",
        "content_font_size": "内容字体大小",
        "11pt_default": "11 点（默认）",
        "ai_reply_lines": "AI 回复行数",
        "1_line_default": "1 行 (默认)",
        "2_lines": "2 行",
        "3_lines": "3 行",
        "5_lines": "5 行",
        "unlimited": "不限制",
        "show_agent_details": "显示代理活动详情",
        "show_tool_status": "紧凑栏显示工具调用详情",
        "force_virtual_notch": "强制使用虚拟刘海",
        "force_virtual_notch_desc": "即使显示器没有物理刘海，也使用可移动的虚拟岛。",
        "live_edit_notch": "实时编辑刘海",
        "live_edit_notch_desc": "直接在当前显示器上调节宽度、水平位置和虚拟刘海高度。",

        "preview_status": "预览状态",
        "processing": "工作中",
        "idle": "空闲",
        "waiting_approval": "等待审批",
        "mascot_speed": "动画速度",
        "speed_off": "关闭",
        "speed_slow": "0.5× 慢速",
        "speed_normal": "1× 正常",
        "speed_fast": "1.5× 快速",
        "speed_very_fast": "2× 极速",
        "mascot_override_per_client": "按客户端覆盖角色",
        "mascot_override_customized": "已自定义 %d 项",
        "mascot_reset_all_overrides": "重置全部角色覆盖",
        "mascot_custom_badge": "自定义",
        "mascot_using_override_format": "当前使用 %@ 角色",
        "mascot_picker_title": "角色",
        "mascot_follow_default": "跟随默认",
        "mascot_reset_override": "重置当前覆盖",

        "enable_sound": "启用音效",
        "volume": "音量",
        "sound_pack": "声音包",
        "sound_pack_catalog": "声音包目录",
        "sound_pack_sync": "同步目录",
        "sound_pack_syncing": "同步中…",
        "sound_pack_sync_complete": "目录已刷新",
        "sound_pack_install": "安装",
        "sound_pack_installing": "安装中…",
        "sound_pack_install_complete": "声音包已安装",
        "sound_pack_use": "使用",
        "sound_pack_in_use": "正在使用",
        "open_sound_pack_folder": "打开声音包目录",
        "session_start": "会话开始",
        "new_claude_session": "新的 Claude Code 会话",
        "task_complete": "任务完成",
        "ai_completed_reply": "AI 完成了本轮回复",
        "completion_pending_review": "待看",
        "completion_next": "下一条",
        "completion_close": "收起",
        "task_error": "任务错误",
        "tool_or_api_error": "工具失败或 API 错误",
        "system_section": "系统",
        "boot_sound": "启动音效",
        "boot_sound_desc": "SuperIsland 启动时播放提示音",
        "interaction": "交互",
        "approval_needed": "需要审批",
        "waiting_approval_desc": "等待权限审批或回答问题",
        "task_confirmation": "任务确认",
        "you_sent_message": "你发送了一条消息",

        "testing_preview_section": "预览场景",
        "testing_preview_scenario": "测试场景",
        "testing_load_preview": "加载预览",
        "testing_clear_preview": "清空测试会话",
        "testing_preview_loaded": "测试场景已加载",
        "testing_preview_cleared": "测试会话已清空",
        "testing_live_checks": "真实链路检查",
        "testing_send_notification": "发送测试通知",
        "testing_send_notification_desc": "向 macOS 发送一条测试横幅，用来确认通知文案、权限和提示音是否正常。",
        "testing_notification_sent": "测试通知已发送",
        "testing_data_section": "会话数据",
        "testing_clear_all_sessions": "清空所有会话记录",
        "testing_clear_all_sessions_desc": "清除 SuperIsland 当前会话、缓存记录，以及已导入的历史快照。",
        "testing_all_sessions_cleared": "所有会话记录已清空",
        "testing_unavailable": "当前尚未连接运行中的 AppState，测试注入暂不可用。",
        "testing_scenario_working": "工作中会话",
        "testing_scenario_working_desc": "注入一条正在执行工具的会话，用来检查紧凑栏和列表排版。",
        "testing_scenario_approval": "审批卡片",
        "testing_scenario_approval_desc": "预览权限审批卡，以及自动展开后的审批交互界面。",
        "testing_scenario_question": "问题卡片",
        "testing_scenario_question_desc": "预览 ask-user 问题流程，检查选项和说明文案展示。",
        "testing_scenario_completion": "完成卡片",
        "testing_scenario_completion_desc": "模拟一条刚完成的会话，验证完成总结卡和切换动画。",
        "testing_scenario_multi": "多会话混合",
        "testing_scenario_multi_desc": "加载多条不同状态的会话，检查分组、滚动和当前选中逻辑。",
        "testing_scenario_busy": "高负载工作区",
        "testing_scenario_busy_desc": "用高活动量、多子代理和并发会话来压测面板表现。",
        "testing_scenario_allcli": "全 CLI 来源",
        "testing_scenario_allcli_desc": "为每个支持的 CLI 注入样例，验证图标、吉祥物和分组展示。",
        "testing_simultaneous_completion_started": "已同时触发 3 个完成会话",
        "testing_simultaneous_completion_button": "同时触发多个完成会话",
        "testing_simultaneous_completion_desc": "立即注入 3 个已完成会话，用来验证队列顺序、详情进入和收起逻辑。",
        "testing_staggered_completion_started": "已开始按 1 秒间隔触发 3 个完成会话",
        "testing_staggered_completion_button": "间隔触发多个完成会话",
        "testing_staggered_completion_desc": "按 1 秒间隔依次注入 3 个完成会话，模拟真实 hook 连续完成的场景。"
    ]
}
