import Foundation

// Keep settings, AI, and skill-platform copy together because these screens share the largest set of form labels.
extension AppText {
    static let settingsAndSkillsStrings: [String: String] = [
        "general": "通用",
        "ai": "AI",
        "skills": "技能",
        "behavior": "行为",
        "appearance": "外观",
        "mascots": "角色",
        "sound": "声音",
        "testing": "测试",
        "hooks": "Hooks",
        "about": "关于",

        "launch_at_login": "登录时打开",
        "display": "显示器",
        "display_mode": "显示模式",
        "display_mode_auto": "自动",
        "display_mode_notch": "刘海",
        "display_mode_menu_bar": "菜单栏",
        "menu_bar_show_detail": "菜单栏显示详情",
        "menu_bar_shortcut_hint_prefix": "默认全局快捷键：",
        "menu_bar_shortcut_hint_suffix": "菜单栏模式下可用它快速打开或收起 SuperIsland，也可以去“快捷键”页修改。",
        "auto": "自动",
        "builtin_display": "内建显示器",
        "main_display": "(主屏)",
        "notch": "(刘海)",
        "usage_monitor_section": "AI 用量",
        "usage_monitor": "后台用量监控",
        "enable_usage_monitor": "启用监控",
        "disable_usage_monitor": "关闭监控",
        "refresh_now": "立即刷新",
        "usage_monitor_enabled": "已启用用量监控",
        "usage_monitor_disabled": "已关闭用量监控",
        "usage_refresh_complete": "用量已刷新",
        "usage_snapshot_empty": "暂时还没有用量快照",
        "usage_cursor_unavailable": "在支持的浏览器里登录 cursor.com 后会显示用量",
        "usage_used": "已用",
        "usage_remaining": "剩余",
        "usage_summary_credits": "额度",
        "usage_summary_unlimited": "不限量",
        "usage_summary_spend_ok": "费用正常",
        "usage_summary_spend_blocked": "费用已封顶",
        "usage_this_month": "本月",
        "usage_this_week": "本周",
        "usage_recent_30_days": "最近30天",
        "usage_breakdown_empty": "当前区间暂无本地 rollout 用量",
        "usage_range_this_week": "本周",
        "usage_range_this_month": "本月",
        "usage_range_recent_30_days": "30天",
        "usage_table_date": "日期",
        "usage_table_model": "模型",
        "usage_table_input": "输入",
        "usage_table_output": "输出",
        "usage_table_total": "总量",
        "usage_table_cost": "费用",
        "usage_tokens": "令牌",
        "codex_accounts_section": "Codex 账号",
        "codex_accounts": "托管的 Codex 账号",
        "codex_accounts_desc": "同步当前 auth.json、导入快照，并切换 CLI / App 正在使用的 Codex 账号。",
        "codex_accounts_empty": "暂时还没有托管的 Codex 账号",
        "codex_account_sync_current": "同步当前 Auth",
        "codex_account_import": "导入 Auth",
        "codex_account_login": "在 Terminal 中登录",
        "codex_account_login_device_auth": "设备码登录",
        "codex_account_active_label": "当前激活",
        "codex_account_current_auth": "当前 Auth",
        "codex_account_active_badge": "激活中",
        "codex_account_activate": "激活",
        "codex_account_remove": "删除",
        "codex_account_sync_complete": "当前 Codex Auth 已同步",
        "codex_account_activate_complete": "Codex 账号已激活",
        "codex_account_remove_complete": "Codex 账号已删除",
        "codex_account_imported": "已导入",
        "codex_account_updated": "已更新",
        "codex_account_skipped": "已跳过",
        "codex_account_login_started": "已经打开 Terminal 进行 Codex 登录。登录完成后，新 auth 会自动保存。",
        "codex_account_login_device_started": "已经打开 Terminal 进行设备码登录。登录完成后，新 auth 会自动保存。",
        "codex_auto_switch": "Codex 自动切号",
        "codex_auto_switch_enable": "启用自动切号",
        "codex_auto_switch_disable": "关闭自动切号",
        "codex_auto_switch_enabled": "Codex 自动切号已启用",
        "codex_auto_switch_disabled": "Codex 自动切号已关闭",
        "codex_auto_switch_run_now": "立即检查",
        "codex_auto_switch_run_complete": "自动切号检查已完成",
        "codex_auto_switch_threshold_5h": "当 5 小时剩余额度低于",
        "codex_auto_switch_threshold_weekly": "当 weekly 剩余额度低于",
        "codex_auto_switch_api_usage": "本地 rollout 数据不新鲜时回退到 usage API",

        "skills_shared_library": "共享技能库",
        "skills_shared_library_desc": "把所有全局 skill 统一放在一个目录里，再把 Claude、Cursor、Gemini 等 agent 链接到同一套技能库。",
        "skills_shared_library_summary": "已安装 %d 个 skill · 已接入 %d 个 agent",
        "skills_external_summary": "检测到 %d 个外部或历史 skill",
        "skills_tabs": "技能分区",
        "skills_tab_library": "技能库",
        "skills_tab_agents": "Agent",
        "skills_tab_marketplace": "市场",
        "skills_install": "安装与导入",
        "skills_install_placeholder": "Git 仓库或 URL，例如 vercel-labs/skills 或 GitLab tree 链接",
        "skills_install_from_github": "从 URL 安装",
        "skills_import_folder": "导入本地目录",
        "skills_install_hint": "支持导入单个 skill 目录，也支持导入包含多个 SKILL.md 的仓库目录。",
        "skills_agent_links": "Agent 链接",
        "skills_link_all_agents": "链接所有支持的 Agent",
        "skills_link": "链接",
        "skills_unlink": "取消链接",
        "skills_resolve_conflict": "解决冲突",
        "skills_resolve_all_conflicts": "解决全部冲突",
        "skills_status_native": "原生",
        "skills_status_linked": "已链接",
        "skills_status_missing": "未接入",
        "skills_status_conflict": "冲突",
        "skills_installed": "已安装技能",
        "skills_empty": "共享技能库里还没有安装任何 skill",
        "skills_installed_search_placeholder": "搜索已安装和外部技能",
        "skills_installed_search_results": "显示 %d / %d 个 skill",
        "skills_installed_search_empty": "没有匹配当前搜索的 skill",
        "skills_show_more": "再显示 %d 个",
        "skills_update": "更新",
        "skills_update_all": "从源仓库更新全部",
        "skills_adopt": "导入到共享库",
        "skills_adopt_all": "导入全部外部技能",
        "skills_delete_confirm_title": "确认删除技能？",
        "skills_delete_confirm_message": "这会把“%@”从磁盘上永久删除。",
        "skills_external": "外部与历史技能",
        "skills_external_hint": "这些 skill 位于 ~/.agents/skills 之外。导入到共享库后可以统一管理。",
        "skills_storage_shared": "共享库",
        "skills_storage_legacy": "历史 .agent",
        "skills_health": "平台健康度",
        "skills_health_external_pending": "还有 %d 个全局 skill 尚未纳入共享库",
        "skills_health_project_scoped": "检测到 %d 个项目级 skill，它们会保留在本地项目中",
        "skills_health_link_conflicts": "有 %d 个 agent 的 skills 目录存在冲突，需要手动处理",
        "skills_marketplace": "热门仓库",
        "skills_marketplace_source": "来源",
        "skills_marketplace_source_all": "全部",
        "skills_marketplace_source_skills_sh": "skills.sh",
        "skills_marketplace_source_mayidata": "Mayidata",
        "skills_marketplace_source_github": "GitHub",
        "skills_marketplace_skills_sh_board": "skills.sh 榜单",
        "skills_marketplace_board_hot": "热门",
        "skills_marketplace_board_trending": "趋势",
        "skills_marketplace_board_all_time": "总榜",
        "skills_refresh_hot": "刷新列表",
        "skills_search_placeholder": "搜索 skill 仓库与来源站点",
        "skills_search": "搜索",
        "skills_open_curated_list": "打开精选列表",
        "skills_marketplace_hint": "skills.sh 和 Mayidata 更适合做 skill 发现；直接安装仍然以当前支持的 GitHub 流程为准。",
        "skills_marketplace_empty": "还没有加载到热门 skill 仓库",
        "skills_marketplace_updated": "更新于 %@",
        "skills_security": "安全提示",
        "skills_security_hint": "安装前先检查 SKILL.md 内容。公开 skill 仓库通常没有经过安全审计，且内容可能随时变化。",
        "open_folder": "打开目录",
        "open": "打开",
        "install": "安装",
        "delete": "删除",
        "preview": "预览",
        "loading_ai_settings": "正在加载 AI 设置…",
        "loading_ai_settings_desc": "用量监控和 Codex 账号状态马上就会显示出来。",
        "open_source": "打开来源",
        "installing": "安装中…"
    ]
}
